/*
 * This source file was generated by the Gradle 'init' task
 */
package main

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import main.typehandler.*

class AppTest {
    @Test
    fun correctHexStringRepresentation() {
        val number = 127.864F
        assertEquals("42FFBA5E", floatToHexString(number))
    }
    @Test
    fun correctSliceToHex() {
        val slice1 = "0100"
        assertEquals('4', sliceToHex(slice1))
        val slice2 = "1110"
        assertEquals('E', sliceToHex(slice2))
    }
    @Test
    fun correctIntToBitString() {
        assertEquals("00000000000000000000000000000000", intToBitString(0))
        assertEquals("01111111111111111111111111111111", intToBitString(Int.MAX_VALUE))
        assertEquals("10000000000000000000000000000000", intToBitString(Int.MIN_VALUE))
    }
    @Test
    fun correctBitStringToFloat() {
        val bitStringPositive = "01000010111111111011101001011110"
        val bitStringNegative = "10111110100000000000000000000000"
        assertEquals(127.864F, bitStringToFloat(bitStringPositive))
        assertEquals(-0.25F, bitStringToFloat(bitStringNegative))
    }
    @Test
    fun testShiftRegisters() {
        val registers = arrayOf(127.864F, 332.584F, 72.33F)
        val shiftPositive = 1
        assertEquals(6332744F, shiftRegisters(registers, shiftPositive))
        val shiftNegative = -1
        assertEquals(-0.00084787083F, shiftRegisters(registers, shiftNegative))
        val noShift = 0
        assertEquals(332.584F, shiftRegisters(registers, noShift))

        val shiftTooMuch = -2
        assertFailsWith<IllegalArgumentException>(
                message = "Register shift must be within -1 to 1",
                block = { shiftRegisters(registers, shiftTooMuch) }
        )
    }
    @Test
    fun testArgParsing(){
        val args = arrayOf("--shift", "-1", "--flip", "false")
        val argMap = parseArgs(args)
        assertEquals("-1", argMap["shift"])
        assertEquals("false", argMap["flip"])
    }
}
